package app.chatlens.ui

import androidx.compose.foundation.Image
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.painterResource
import app.chatlens.R

/**
 * ChatLens mark: a speech bubble with the three AI stars (no magnifying glass). The vector file ic_logo_mark.xml is generated by tools/make_logo.py
 * from the chosen variant (see PLAN.md section 22). Image only, no text.
 */
@Composable
fun LogoMark(modifier: Modifier = Modifier, description: String? = null) {
    Image(painterResource(R.drawable.ic_logo_mark), contentDescription = description, modifier = modifier)
}
